# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05c6501d65795555cc71079d41225599e22b7d7b9f927fabf88f0922d727b952a81db22a9d397ecd87943d2bbfe9f67737e3d3bbb124529816656f8fd2b71ca3

test:
  secret_key_base: b53f1723dacc305d5b0a478ad29ba841b22b70598ca9e1fcef1673d3de6e7ba4a63cc8d8fed4e844fb97132f5a547e228f34bf2d7771fb842486cc805ff1fcdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
